name: tealwave
description: TealWave - Offline Music Player
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  palette_generator: ^0.3.3+3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  rxdart: ^0.27.7
  path_provider: ^2.1.2

flutter:
  uses-material-design: true
